name: Build and deploy GH Pages

on:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  pages: write

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v6
      # Build & deploy
      - name: Deploy to gh-pages branch
        uses: shalzz/zola-deploy-action@v0.22.1
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Worker token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}